update job

diff --git a/.github/workflows/keep-warm.yml b/.github/workflows/keep-warm.yml
--- a/.github/workflows/keep-warm.yml
+++ b/.github/workflows/keep-warm.yml
@@ -8,9 +8,19 @@ on:
 jobs:
   ping:
     runs-on: ubuntu-latest
+    continue-on-error: true
     steps:
       - name: Ping homepage
+        id: ping
         run: |
           STATUS=$(curl -k --retry 3 --retry-delay 5 -s -o /dev/null -w "%{http_code}" https://danutakoziello-doherty.co.uk/ || echo "000")
-          echo "Response code: $STATUS"
-          exit 0
+          echo "status=$STATUS" >> $GITHUB_OUTPUT
+
+          # jeśli status nie jest w zakresie 200–399 -> fail
+          if [ "$STATUS" -lt 200 ] || [ "$STATUS" -ge 400 ]; then
+            echo "Bad status: $STATUS"
+            exit 1
+          fi
+
+      - name: Result ${{ steps.ping.outputs.status }}
+        run: echo "Response was ${{ steps.ping.outputs.status }}"
